{
 "title": "FritzHosts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "show tag values from \"FritzHosts\" WITH KEY =~ //"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Status of $hostname",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "alias": "raspi4kodi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FritzHosts",
     "query": "SELECT distinct(\"active\") FROM \"FritzHosts\" WHERE (\"hostname\" = 'raspi4kodi') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "$hostname" }
     ]
    }
   ]
  },
  {
   "title": "List",
   "type": "table-old",
   "gridPos": { "h": 23, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "FritzHosts",
     "query": "SELECT distinct(\"active\") AS \"online\" FROM \"FritzHosts\" WHERE (\"time\" > now()-5m AND \"field(active)\" != 'null') AND $timeFilter GROUP BY time($__interval), \"hostname\"",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "online" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "time", "operator": ">", "value": "now()-5m" },
      { "condition": "AND", "key": "field(active)", "operator": "!=", "value": "null" }
     ]
    }
   ]
  },
  {
   "title": "$hostname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Fritzbox",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FritzHosts",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "SuperDuperDings" }
     ]
    },
    {
     "alias": "$hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "FritzHosts",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "$hostname" }
     ]
    }
   ]
  },
  {
   "title": "Count Online Devices",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FritzHosts",
     "select": [
      [
       { "params": [ "active" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}