{
 "title": "Raumklima per Room",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Room",
    "query": "Torben, Bad, Eleen, Hanno, Kueche, Wohnzimmer"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature - $Room",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"temperature\") FROM \"Raumklima\" WHERE ( \"room\" = '$Room') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "$Room" }
     ]
    }
   ]
  },
  {
   "title": "CO2 - $Room",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"CO2\") FROM \"Raumklima\" WHERE (\"room\" = '$Room') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "CO2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "$Room" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  },
  {
   "title": "Humidity - $Room",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"humidity\") FROM \"Raumklima\" WHERE  ( \"room\" = '$Room')  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "$Room" }
     ]
    }
   ]
  },
  {
   "title": "Pressure - $Room",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"pressure\") FROM \"Raumklima\" WHERE  (\"room\" = '$Room')  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "$Room" }
     ]
    }
   ]
  }
 ]
}