{
 "title": "Raumklima per Device",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "T-ESP32-1,T-ESP32-2,T-ESP32-3,T-ESP32-4,T-ESP32-5,T-ESP32-6"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature - $Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$Device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"temperature\") FROM \"Raumklima\" WHERE ( \"device\" = '$Device') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "$Room" }
     ]
    }
   ]
  },
  {
   "title": "CO2 - $Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "alias": "$Device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"CO2\") FROM \"Raumklima\" WHERE (\"device\" = '$Device') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "CO2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "$Room" },
      { "condition": "OR", "key": "device", "operator": "=", "value": "$Device" }
     ]
    }
   ]
  },
  {
   "title": "Humidity - $Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "$Device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"humidity\") FROM \"Raumklima\" WHERE  ( \"device\" = '$Device')  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "$Room" }
     ]
    }
   ]
  },
  {
   "title": "Pressure - $Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "$Device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"pressure\") FROM \"Raumklima\" WHERE  (\"device\" = '$Device')  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=", "value": "$Room" }
     ]
    }
   ]
  },
  {
   "title": "Illuminance - $Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "alias": "$Device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Raumklima",
     "query": "SELECT mean(\"pressure\") FROM \"Raumklima\" WHERE  (\"device\" = '$Device')  AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "illuminance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  }
 ]
}